# Define a dictionary

country = {
    "ARE": "united arab emirates",
    "ARG": "argentina",
    "AUS": "australia",
    "AUT": "austria",
    "BEL": "belgium",
    "BGD": "bangladesh",
    "BGR": "bulgaria",
    "BHS": "bahamas",
    "BIH": "bosnia and herzegovina",
    "BRA": "brazil",
    "CAN": "canada",
    "CHE": "switzerland",
    "CHL": "chile",
    "COL": "colombia",
    "CYP": "cyprus",
    "DEU": "germany",
    "DOM": "dominican republic",
    "DZA": "algeria",
    "EGY": "egypt",
    "ESP": "spain",
    "EST": "estonia",
    "FIN": "finland",
    "FRA": "france",
    "GBR": "united kingdom",
    "GRC": "greece",
    "HKG": "hong kong",
    "HRV": "croatia",
    "HUN": "hungary",
    "IDN": "indonesia",
    "IND": "india",
    "IRL": "ireland",
    "ISR":"israel",
    "ITA": "italy",
    "JOR": "jordan",
    "JPN": "japan",
    "KEN": "kenya",
    "KW": "kuwait",
    "LVA": "latvia",
    "MAR": "morocco",
    "MEX": "mexico",
    "MKD": "macedonia",
    "MYS": "malaysia",
    "NLD": "netherlands",
    "NPL": "nepal",
    "PAK": "pakistan",
    "PER": "peru",
    "PHL": "philippines",
    "POL": "poland",
    "PRI": "puerto rico",
    "PRT": "portugal",
    "ROU": "romania",
    "RUS": "russia",
    "SGP": "singapore",
    "SLV": "el salvador",
    "SRB": "serbia",
    "SVK": "slovakia",
    "SWE": "sweden",
    "TUR": "turkey",
    "TZA": "tanzania",
    "UGA": "uganda",
    "UKR": "ukraine",
    "URY": "uruguay",
    "USA": "united states",
    "VEN": "venezuela",
    "VNM": "vietnam",
    "ZAF": "south africa"
}