# Generated by Django 5.0.6 on 2024-11-18 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_task2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Channel', models.CharField(max_length=50)),
                ('Mean_Trust_Score', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('Median_Trust_Score', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('Standard_Deviation', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('Sample_Size', models.IntegerField(default=0)),
                ('Min_Score', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('Max_Score', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Task5_high',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=2000)),
                ('airline_sentiment_gold', models.CharField(max_length=50)),
                ('predicted_sentiment', models.CharField(max_length=50)),
                ('correct', models.IntegerField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Task5_low',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=2000)),
                ('airline_sentiment_gold', models.CharField(max_length=50)),
                ('predicted_sentiment', models.CharField(max_length=50)),
                ('correct', models.IntegerField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.userprofile')),
            ],
        ),
    ]
