# Generated by Django 5.0.6 on 2024-11-20 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_task3'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task5_high',
            old_name='airline_sentiment_gold',
            new_name='Actual_Sentiment',
        ),
        migrations.RenameField(
            model_name='task5_high',
            old_name='correct',
            new_name='Correct',
        ),
        migrations.RenameField(
            model_name='task5_high',
            old_name='predicted_sentiment',
            new_name='Predicted_Sentiment',
        ),
        migrations.RenameField(
            model_name='task5_high',
            old_name='text',
            new_name='Text',
        ),
    ]
